include_recipe 'vm-setup::user_creation'
include_recipe 'vm-setup::apt_update'
include_recipe 'vm-setup::gui_install'
include_recipe 'vm-setup::dir_creation'
include_recipe 'vm-setup::file_download'
include_recipe 'vm-setup::package_install'
include_recipe 'vm-setup::configure_plex'
include_recipe 'vm-setup::configure_chromium'
include_recipe 'vm-setup::picture_install'

